config/routes.rb
VenueManagement::Application.routes.draw do

  resources :venues
  
  resources :contacts

end

app/models/attraction.rb
class Attraction < ActiveRecord::Base
  belongs_to :venue
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :venue
end

app/models/meeting_room.rb
class MeetingRoom < ActiveRecord::Base
  belongs_to :venue
end

app/models/nearby_facility.rb
class NearbyFacility < ActiveRecord::Base
  belongs_to :venue
end

app/models/style.rb
class Style < ActiveRecord::Base
  belongs_to :venue
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  has_many :contact
  has_many :attraction
  has_many :nearby_facility
  has_many :style
  has_many :meeting_room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.xml
  def index
    @contacts = Contact.all
    
    respond_to do |format|
      format.html #index.html.erb
      format.xml { render :xml => @contacts }
    end
  end
  
  # GET /contacts/1
  # GET /contacts/1.xml
  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.xml
  def new
    @contact = Contact.new
    
    respond_to do |format|
      format.html #new.html.erb
      format.xml { render :xml => @contact }
    end
  end
  
   # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end
  
  # POST /contacts
  # POST /contacts.xml
  def create
    @contact = Contact.new(params[:contact])
    
    respond_to do |format|
      
      if @contact.save
        format.html { redirect_to(contacts_path, :notice => 'Contact was successfully created.') }
      else
        format.html {render :action => "new" }
      end 
    end
  end
  
  # POST /contacts
  # POST /contacts.xml
  def update
    @contact = Contact.find(params[:contact])
    
    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to(@contact, :notice => "Contact was successfully updated.")}
        format.xml { head :ok }
       else
         format.html { render :action => "edit"}
         format.xml { render :xml => @contact.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  #DELETE /contacts/1
  #DELETE /contacts/1.xml
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    
    respond_to do |format|
      format.html { redirect_to(contacts_url)}
      format.xml { head :ok } 
    end
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  # GET /venues
  # GET /venues.xml
  def index
    @venues = Venue.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @venues }
    end
  end

  # GET /venues/1
  # GET /venues/1.xml
  def show
    @venue = Venue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @venue }
    end
  end

  # GET /venues/new
  # GET /venues/new.xml
  def new
    @venue = Venue.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @venue }
    end
  end

  # GET /venues/1/edit
  def edit
    @venue = Venue.find(params[:id])
  end

  # POST /venues
  # POST /venues.xml
  def create
    @venue = Venue.new(params[:venue])

    respond_to do |format|
      if @venue.save
        format.html { redirect_to(@venue, :notice => 'Venue was successfully created.') }
        format.xml  { render :xml => @venue, :status => :created, :location => @venue }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @venue.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /venues/1
  # PUT /venues/1.xml
  def update
    @venue = Venue.find(params[:id])

    respond_to do |format|
      if @venue.update_attributes(params[:venue])
        format.html { redirect_to(@venue, :notice => 'Venue was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @venue.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.xml
  def destroy
    @venue = Venue.find(params[:id])
    @venue.destroy

    respond_to do |format|
      format.html { redirect_to(venues_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/contacts/_form.html.erb
<%= form_for (@contact) do |f| %>
	<% if @contact.errors.any? %>
		<div id="error_explanation">
			
			<h2>Error occured</h2>
		</div>
	<% end %>
	
<div class="field">
	<%= f.label :contact_name%>
	<%= f.text_field :contact_name %>
</div>

<div class="field">
	<%= f.label :contact_role %>
	<%= f.text_field :contact_role %>
</div>

<div class="actions">
	<%= f.submit %>
</div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Edit Contact</h1>

<%= render 'form'%>

<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Contacts</h1>
<%= link_to 'New Contact', new_contact_path %>
<table>
	<tr>
		<th>Contact Name</th>
		<th>Contact Role</th>
		
	</tr>
	<%- for contact in @contacts %>
		<tr>
			<td><%= contact.contact_name %></td>
			<td><%= contact.contact_role %></td>
			
		</tr>
	<%- end%>
</table>

app/views/contacts/new.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
  <head>
	  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	  <title>new.html</title>
	  <%= javascript_include_tag :defaults %>
	  <%= yield :head %>
  </head>
  <body>
  	<h1>New Contact</h1>
  <%= render 'form' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VenueManagement</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/venues/_form.html.erb
<%= form_for(@venue) do |f| %>
  <% if @venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% @venue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="field">
  	<%= f.label :postcode%>
  	<%= f.text_field :postcode%>
  </div>
  <div class="field">
  	<%= f.label :telephone%>
  	<%= f.text_field :telephone%>
  </div>
  <div class="field">
  	<%= f.label :fax%>
  	<%= f.text_field :fax%>
  </div>
  <div class="field">
  	<%= f.label :website%>
  	<%= f.text_field :website%>
  </div>
  <div class="field">
  	<%= f.label :delegate_rates%>
  	<%= f.text_field :delegate_rates%>
  </div>
  <div class="field">
  	<%= f.label :room_hire_rates%>
  	<%= f.text_field :room_hire_rates%>
  </div>
  <div class="field">
  	<%= f.label :meeting_capacity%>
  	<%= f.text_field :meeting_capacity%>
  </div>
  <div class="field">
  	<%= f.label :catering_capacity%>
  	<%= f.text_field :catering_capacity%>
  </div>
  <div class="field">
  	<%= f.label :no_bedrooms%>
  	<%= f.text_field :no_bedrooms%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/venues/edit.html.erb
<h1>Edit Venue</h1>

<%= render 'form' %>

<%= link_to 'Show', @venue %> | <%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<table>
	<tr><th>venue name</th></tr>
<%- for venue in @venues %>
<tr><td><%= venue.name %></td></tr>
<%- end %>

</table>
<br />

<%= link_to 'New Venue', new_venue_path %>

app/views/venues/new.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
  <head>
	  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	  <title>New Venue</title>
	  <%= javascript_include_tag :defaults %>
	  <%= yield :head %>
  </head>
  <body>
  <%= yield %>
 
 <label>New Venue</label>
 <%= render 'form' %>
  </body>
</html>

app/views/venues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @venue.name %>
</p>

<p>
  <b>Address:</b>
  <%= @venue.address %>
</p>

<p>
  <b>Postcode:</b>
  <%= @venue.postcode %>
</p>

<p>
  <b>Telephone:</b>
  <%= @venue.telephone %>
</p>

<p>
  <b>Fax:</b>
  <%= @venue.fax %>
</p>

<p>
  <b>Website:</b>
  <%= @venue.website %>
</p>

<p>
  <b>Delegate rates:</b>
  <%= @venue.delegate_rates %>
</p>

<p>
  <b>Room hire rates:</b>
  <%= @venue.room_hire_rates %>
</p>

<p>
  <b>Meeting capacity:</b>
  <%= @venue.meeting_capacity %>
</p>

<p>
  <b>Catering capacity:</b>
  <%= @venue.catering_capacity %>
</p>

<p>
  <b>No bedrooms:</b>
  <%= @venue.no_bedrooms %>
</p>


<p><% for room in Venue.find(@venue.id).meeting_room do %></p>
<%= link_to room.name, meeting_room_url(room) %>
<% end %>

<%= link_to 'Edit', edit_venue_path(@venue) %> |
<%= link_to 'Back', venues_path %>